include $(GNUSTEP_MAKEFILES)/common.make


TOOL_NAME = Test
Test_HEADERS = PgConn.h PgStmt.h DbTemplates.h Database.h Statement.h \
	       DatabaseFactory.h MySQLConn.h
Test_OBJC_FILES = test.m PgConn.m PgStmt.m DbTemplates.m DatabaseFactory.m \
		  MySQLConn.m

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/tool.make


